

name: IvanYa

on:
  push:
    branches: 
        -master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       
      - name: hello brother
        run : echo "Hello, world!"
  myprod:
    runs-on: ubuntu-latest
    steps:
    - name: prod
      run : echo "worldd"
